### ISSUE TITLE
possible to use mailgun smtp server?

### ISSUE THREAD

**Issue by ralyodio** [guillaumebriday/lobsters-docker#3]
The email environment variables appear to be ignored.

```
ENV SMTP_HOST="mg.fullstacknews.com" \
    SMTP_PORT="25" \
    SMTP_STARTTLS_AUTO="true" \
    SMTP_USERNAME="postmaster@mg.fullstacknews.com" \
    SMTP_PASSWORD="xxx"
```

**Comment by guillaumebriday** [comment]
There are not for me.

In console:
```bash
$ docker-compose run --rm lobsters rails c
$ ENV.fetch("SMTP_PORT", 33535)
=> 25
```

I got 25 as excepted.

As you can see in the Lobsters repo, these variables are use for SMTP config: https://github.com/lobsters/lobsters/blob/master/config/initializers/email.rb

Could you give me more details please ?
