### ISSUE TITLE
DB configuration issue

### ISSUE THREAD

**Issue by pixeye33** [guillaumebriday/lobsters-docker#6]
Hello,

I've tried your docker image at it seems more fit than the one you are based on (auto provisioning mostly).

It seems that there is an issue, as i have this in my logs
`Mysql2::Error::ConnectionError: Access denied for user 'root'@'172.22.0.3' (using password: YES)`

Even though i have setup the env variable
`DB_USER=lobsters`

I've seen no root hardcoded in your code, no idea what the issue is. FYI i do not have this issue with utensils version.

Thanks for you work on this container 👍

**Comment by guillaumebriday** [comment]
Hey!

I do not provide the mysql example configuration.

It looks like your host is wrong. Can you show me your configuration file ? (without your password)

As you can see [here](https://github.com/guillaumebriday/lobsters-docker/blob/master/Dockerfile#L10), I hardcoded the host with the name of the [docker-compose service](https://github.com/guillaumebriday/lobsters-docker/blob/master/docker-compose.yml#L4) for the example

That is why in the readme, I defined a name for my mysql container : `docker run --name lobsters-db [...]`

Same [here](https://github.com/guillaumebriday/selfhosted-services/blob/master/roles/lobsters/tasks/main.yml#L13) in my ansible playbook that I use to deploy my personal lobsters. 

I think you just need to override it with the correct host and you should be good to go.

Thanks

**Comment by pixeye33** [comment]
Thanks for your quick answer !

I guess you missed the point :
logs says **root** even though i have the env variable set to **lobsters**

Even if i had the DB_HOST wrong i shouldn't see **root** anywhere.

I override most of the ENV variables contained inside your Dockerfile with my docker-compose including DB_HOST to the correct name.

FYI : i'm using the mariadb `/docker-entrypoint-initdb.d` folder to setup the database so my apps doesn't use a root account.

**Comment by guillaumebriday** [comment]
Hum, I think you're right, my bad!

I need to retry but I didn't catch this bug because I use the default config.

I will switch to the default `DATABASE_URL` environment variable instead of spliting the config in multiple variables.

Or add a `COPY` in the Dockerfile for a custom `database.yml`.

what do you think ?

**Comment by ralyodio** [comment]
Docker suspports .env

**Comment by guillaumebriday** [comment]
I know @chovy. What's your point ? 🤔

**Comment by ralyodio** [comment]
That would be a better way to handle env variables imo.

**Comment by pixeye33** [comment]
I've made a quick and dirty test by using
`-e DATABASE_URL=mysql2://lobsters:lobsterspw@lobsters-db/lobsters`
**in addition** to the others env variables : i see no root mention anymore !

`docker run --name lobsters -p 3000:3000 -e DB_USER=lobsters -e DB_PASSWORD=lobsterspw guillaumebriday/lobsters-docker`
VS
`docker run --name lobsters -p 3000:3000 -e DB_USER=lobsters -e DB_PASSWORD=lobsterspw -e DATABASE_URL=mysql2://lobsters:lobsterspw@lobsters-db/lobsters guillaumebriday/lobsters-docker`

(with no database actually started, as i am lazy)

DATABASE_URL would be a good/elegant fix for sure !
Having a file COPY with a conf inside the image, not really (even though it can be overwritten with a volume).

**Comment by pixeye33** [comment]
I can confirm it works by just switching from :
```yaml
- DB_HOST=lobsters-db
- DB_USER=lobsters
- DB_PASSWORD=lobsterspw
- DB_DATABASE=lobsters
```
to :
```yaml
- DATABASE_URL=mysql2://lobsters:lobsterspw@lobsters-db:3306/lobsters
```

**Comment by guillaumebriday** [comment]
I completely forgot that I added a `config/database.yml` file with custom environment variables in the first place.

The issue was the typo here https://github.com/guillaumebriday/lobsters-docker/pull/7/files#diff-e31bdf70b15c8f84344c332efe06900dL7

`DB_USER` instead of `DB_USERNAME`.

Anyway, thank you @pixeye33 !!
